# Generated by Django 5.2.8 on 2025-11-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=50, verbose_name='фамилия')),
                ('imy', models.CharField(max_length=50, verbose_name='имя')),
                ('otchestvo', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_years', models.IntegerField(verbose_name='год рождения')),
                ('group_number', models.CharField(max_length=10, verbose_name='номер группы')),
            ],
        ),
    ]
